// <auto-generated />
using System;
using Labb1MVC_Simon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1MVC_Simon.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20220922114627_updatecust")]
    partial class updatecust
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Amount = 2,
                            LoanId = 6
                        },
                        new
                        {
                            BookId = 2,
                            Amount = 5,
                            LoanId = 26
                        },
                        new
                        {
                            BookId = 3,
                            Amount = 1,
                            LoanId = 18
                        },
                        new
                        {
                            BookId = 4,
                            Amount = 3,
                            LoanId = 22
                        },
                        new
                        {
                            BookId = 5,
                            Amount = 5,
                            LoanId = 24
                        },
                        new
                        {
                            BookId = 6,
                            Amount = 4,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 7,
                            Amount = 3,
                            LoanId = 8
                        },
                        new
                        {
                            BookId = 8,
                            Amount = 2,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 9,
                            Amount = 4,
                            LoanId = 5
                        },
                        new
                        {
                            BookId = 10,
                            Amount = 3,
                            LoanId = 14
                        },
                        new
                        {
                            BookId = 11,
                            Amount = 4,
                            LoanId = 27
                        },
                        new
                        {
                            BookId = 12,
                            Amount = 2,
                            LoanId = 9
                        },
                        new
                        {
                            BookId = 13,
                            Amount = 1,
                            LoanId = 21
                        },
                        new
                        {
                            BookId = 14,
                            Amount = 3,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 15,
                            Amount = 2,
                            LoanId = 14
                        },
                        new
                        {
                            BookId = 16,
                            Amount = 3,
                            LoanId = 35
                        },
                        new
                        {
                            BookId = 17,
                            Amount = 3,
                            LoanId = 11
                        },
                        new
                        {
                            BookId = 18,
                            Amount = 5,
                            LoanId = 31
                        },
                        new
                        {
                            BookId = 19,
                            Amount = 4,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 20,
                            Amount = 4,
                            LoanId = 34
                        },
                        new
                        {
                            BookId = 21,
                            Amount = 2,
                            LoanId = 39
                        },
                        new
                        {
                            BookId = 22,
                            Amount = 5,
                            LoanId = 2
                        },
                        new
                        {
                            BookId = 23,
                            Amount = 2,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 24,
                            Amount = 3,
                            LoanId = 16
                        },
                        new
                        {
                            BookId = 25,
                            Amount = 3,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 26,
                            Amount = 1,
                            LoanId = 6
                        },
                        new
                        {
                            BookId = 27,
                            Amount = 3,
                            LoanId = 40
                        },
                        new
                        {
                            BookId = 28,
                            Amount = 5,
                            LoanId = 34
                        },
                        new
                        {
                            BookId = 29,
                            Amount = 2,
                            LoanId = 8
                        },
                        new
                        {
                            BookId = 30,
                            Amount = 5,
                            LoanId = 40
                        },
                        new
                        {
                            BookId = 31,
                            Amount = 2,
                            LoanId = 15
                        },
                        new
                        {
                            BookId = 32,
                            Amount = 4,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 33,
                            Amount = 2,
                            LoanId = 40
                        },
                        new
                        {
                            BookId = 34,
                            Amount = 5,
                            LoanId = 24
                        },
                        new
                        {
                            BookId = 35,
                            Amount = 5,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 36,
                            Amount = 1,
                            LoanId = 27
                        },
                        new
                        {
                            BookId = 37,
                            Amount = 5,
                            LoanId = 31
                        },
                        new
                        {
                            BookId = 38,
                            Amount = 4,
                            LoanId = 2
                        },
                        new
                        {
                            BookId = 39,
                            Amount = 4,
                            LoanId = 38
                        },
                        new
                        {
                            BookId = 40,
                            Amount = 5,
                            LoanId = 33
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Rahul Wells 1019",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/798.jpg",
                            FullName = "Jairo Herman",
                            LoanId = 7,
                            Phone = "816-481-7825"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Brooke Crossing 1145",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/285.jpg",
                            FullName = "Maida Hudson",
                            LoanId = 11,
                            Phone = "555-999-9396"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Wilburn Roads 24",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1053.jpg",
                            FullName = "Alyce Dare",
                            LoanId = 22,
                            Phone = "611-727-9688"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Collier Ford 1182",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/452.jpg",
                            FullName = "Helena Ward",
                            LoanId = 6,
                            Phone = "565-205-8029"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Shane Green 414",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/869.jpg",
                            FullName = "Aaron Denesik",
                            LoanId = 12,
                            Phone = "767-362-3992"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Herman Ports 1885",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/876.jpg",
                            FullName = "Eulalia Boyer",
                            LoanId = 39,
                            Phone = "838-306-8347"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Murazik Lights 1403",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/655.jpg",
                            FullName = "Marcelina Metz",
                            LoanId = 33,
                            Phone = "234-307-4053"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Casper Landing 574",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/335.jpg",
                            FullName = "Ariel Breitenberg",
                            LoanId = 11,
                            Phone = "788-551-4098"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Stiedemann Forges 161",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/216.jpg",
                            FullName = "Domenica Simonis",
                            LoanId = 2,
                            Phone = "636-240-6744"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Will Drives 1130",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/708.jpg",
                            FullName = "Julien Schamberger",
                            LoanId = 30,
                            Phone = "951-323-2993"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Jaylan Points 1197",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1209.jpg",
                            FullName = "Berneice D'Amore",
                            LoanId = 4,
                            Phone = "919-471-9860"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Lubowitz Valleys 208",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/60.jpg",
                            FullName = "Citlalli Bauch",
                            LoanId = 20,
                            Phone = "412-812-9868"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Aurelio Greens 482",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/626.jpg",
                            FullName = "Dulce Corkery",
                            LoanId = 34,
                            Phone = "778-272-9698"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Kutch Meadows 197",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/791.jpg",
                            FullName = "Myrna Thiel",
                            LoanId = 31,
                            Phone = "664-539-8575"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Aida Islands 1711",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/163.jpg",
                            FullName = "Abel Mertz",
                            LoanId = 20,
                            Phone = "814-550-6292"
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "Murphy Greens 1293",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/892.jpg",
                            FullName = "Jerrold Parker",
                            LoanId = 6,
                            Phone = "346-878-7924"
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "Alysson Meadows 498",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1231.jpg",
                            FullName = "Jovany Weber",
                            LoanId = 12,
                            Phone = "541-303-3266"
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "Coy Landing 2058",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/828.jpg",
                            FullName = "Lela Considine",
                            LoanId = 21,
                            Phone = "819-255-1329"
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "Hegmann Forges 2254",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/683.jpg",
                            FullName = "Frederic Rau",
                            LoanId = 38,
                            Phone = "625-752-1882"
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "Schoen View 414",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/619.jpg",
                            FullName = "Marilou Hoppe",
                            LoanId = 14,
                            Phone = "804-264-2502"
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "Durgan Green 2178",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1148.jpg",
                            FullName = "Sedrick McCullough",
                            LoanId = 36,
                            Phone = "668-357-5196"
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "Bogisich Forest 662",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/188.jpg",
                            FullName = "Bennett Rosenbaum",
                            LoanId = 6,
                            Phone = "684-221-2349"
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "Graciela Creek 760",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/244.jpg",
                            FullName = "Emmy Yundt",
                            LoanId = 10,
                            Phone = "734-797-8587"
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "Lesch Parks 2416",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/304.jpg",
                            FullName = "Angie Stehr",
                            LoanId = 13,
                            Phone = "302-732-2134"
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "Willms Manor 146",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/356.jpg",
                            FullName = "Myrtis Cassin",
                            LoanId = 37,
                            Phone = "336-234-2486"
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "Parker Junctions 2394",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1055.jpg",
                            FullName = "Berta Conroy",
                            LoanId = 39,
                            Phone = "738-239-8807"
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "Spencer Glens 1179",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/935.jpg",
                            FullName = "Effie Gerlach",
                            LoanId = 18,
                            Phone = "414-987-4481"
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "Waino Glen 1895",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/532.jpg",
                            FullName = "Erick Macejkovic",
                            LoanId = 21,
                            Phone = "656-926-1971"
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "Al Junctions 2335",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1199.jpg",
                            FullName = "Eliane Stracke",
                            LoanId = 1,
                            Phone = "739-904-3075"
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "Wilbert Mills 791",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1091.jpg",
                            FullName = "Lew Paucek",
                            LoanId = 1,
                            Phone = "428-381-7489"
                        },
                        new
                        {
                            CustomerId = 31,
                            Address = "Lula Court 327",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1096.jpg",
                            FullName = "Jayme Mitchell",
                            LoanId = 25,
                            Phone = "281-388-0229"
                        },
                        new
                        {
                            CustomerId = 32,
                            Address = "Douglas Mall 1265",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/817.jpg",
                            FullName = "Paula Dibbert",
                            LoanId = 31,
                            Phone = "845-424-7218"
                        },
                        new
                        {
                            CustomerId = 33,
                            Address = "Neha Crest 1361",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1101.jpg",
                            FullName = "Angeline McLaughlin",
                            LoanId = 6,
                            Phone = "364-812-8715"
                        },
                        new
                        {
                            CustomerId = 34,
                            Address = "Goodwin Keys 324",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/990.jpg",
                            FullName = "Toni Hickle",
                            LoanId = 23,
                            Phone = "991-942-6712"
                        },
                        new
                        {
                            CustomerId = 35,
                            Address = "Adelia Valley 1267",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/75.jpg",
                            FullName = "Jadyn Quitzon",
                            LoanId = 16,
                            Phone = "411-223-1619"
                        },
                        new
                        {
                            CustomerId = 36,
                            Address = "Yundt Stravenue 2124",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/584.jpg",
                            FullName = "Norma Ferry",
                            LoanId = 32,
                            Phone = "510-383-7372"
                        },
                        new
                        {
                            CustomerId = 37,
                            Address = "Madie Knoll 281",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1204.jpg",
                            FullName = "Elsie Kub",
                            LoanId = 7,
                            Phone = "799-471-2393"
                        },
                        new
                        {
                            CustomerId = 38,
                            Address = "Herzog Groves 2310",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/163.jpg",
                            FullName = "Karl Stoltenberg",
                            LoanId = 7,
                            Phone = "942-498-0128"
                        },
                        new
                        {
                            CustomerId = 39,
                            Address = "Durgan Forge 1396",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1098.jpg",
                            FullName = "Carmella Weissnat",
                            LoanId = 31,
                            Phone = "842-557-2446"
                        },
                        new
                        {
                            CustomerId = 40,
                            Address = "Lehner Terrace 2416",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/210.jpg",
                            FullName = "Laila Barrows",
                            LoanId = 2,
                            Phone = "407-989-0582"
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookLoanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BookReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysToLoan")
                        .HasColumnType("int");

                    b.Property<bool?>("ReturnedInTime")
                        .HasColumnType("bit");

                    b.HasKey("LoanId");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            BookId = 22,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(8945),
                            CustomerId = 35,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 2,
                            BookId = 14,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9361),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 3,
                            BookId = 33,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9375),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 4,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9381),
                            CustomerId = 37,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 5,
                            BookId = 32,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9387),
                            CustomerId = 38,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 6,
                            BookId = 25,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9392),
                            CustomerId = 8,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 7,
                            BookId = 17,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9398),
                            CustomerId = 26,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 8,
                            BookId = 15,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9403),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 9,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9408),
                            CustomerId = 20,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 10,
                            BookId = 35,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9413),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 11,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9418),
                            CustomerId = 6,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 12,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9423),
                            CustomerId = 25,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 13,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9429),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 14,
                            BookId = 11,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9434),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 15,
                            BookId = 15,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9445),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 16,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9452),
                            CustomerId = 5,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 17,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9457),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 18,
                            BookId = 28,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9462),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 19,
                            BookId = 35,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9467),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 20,
                            BookId = 15,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9472),
                            CustomerId = 24,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 21,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9477),
                            CustomerId = 33,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 22,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9482),
                            CustomerId = 38,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 23,
                            BookId = 33,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9488),
                            CustomerId = 1,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 24,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9492),
                            CustomerId = 12,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 25,
                            BookId = 18,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9497),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 26,
                            BookId = 8,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9502),
                            CustomerId = 26,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 27,
                            BookId = 16,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9507),
                            CustomerId = 39,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 28,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9512),
                            CustomerId = 12,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 29,
                            BookId = 8,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9517),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 30,
                            BookId = 4,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9522),
                            CustomerId = 22,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 31,
                            BookId = 33,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9527),
                            CustomerId = 15,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 32,
                            BookId = 26,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9532),
                            CustomerId = 14,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 33,
                            BookId = 29,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9537),
                            CustomerId = 37,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 34,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9542),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 35,
                            BookId = 26,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9547),
                            CustomerId = 35,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 36,
                            BookId = 30,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9552),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 37,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9557),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 38,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9562),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 39,
                            BookId = 5,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9567),
                            CustomerId = 21,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 40,
                            BookId = 4,
                            BookLoanDate = new DateTime(2022, 9, 22, 13, 46, 26, 578, DateTimeKind.Local).AddTicks(9572),
                            CustomerId = 12,
                            DaysToLoan = 30
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.HasOne("Labb1MVC_Simon.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1MVC_Simon.Models.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
