// <auto-generated />
using System;
using Labb1MVC_Simon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1MVC_Simon.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20220922072931_names")]
    partial class names
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Amount = 3,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 2,
                            Amount = 2,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 3,
                            Amount = 3,
                            LoanId = 36
                        },
                        new
                        {
                            BookId = 4,
                            Amount = 4,
                            LoanId = 35
                        },
                        new
                        {
                            BookId = 5,
                            Amount = 1,
                            LoanId = 22
                        },
                        new
                        {
                            BookId = 6,
                            Amount = 5,
                            LoanId = 18
                        },
                        new
                        {
                            BookId = 7,
                            Amount = 5,
                            LoanId = 25
                        },
                        new
                        {
                            BookId = 8,
                            Amount = 3,
                            LoanId = 25
                        },
                        new
                        {
                            BookId = 9,
                            Amount = 1,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 10,
                            Amount = 2,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 11,
                            Amount = 5,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 12,
                            Amount = 3,
                            LoanId = 2
                        },
                        new
                        {
                            BookId = 13,
                            Amount = 4,
                            LoanId = 25
                        },
                        new
                        {
                            BookId = 14,
                            Amount = 2,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 15,
                            Amount = 4,
                            LoanId = 9
                        },
                        new
                        {
                            BookId = 16,
                            Amount = 5,
                            LoanId = 32
                        },
                        new
                        {
                            BookId = 17,
                            Amount = 3,
                            LoanId = 1
                        },
                        new
                        {
                            BookId = 18,
                            Amount = 1,
                            LoanId = 25
                        },
                        new
                        {
                            BookId = 19,
                            Amount = 4,
                            LoanId = 20
                        },
                        new
                        {
                            BookId = 20,
                            Amount = 1,
                            LoanId = 9
                        },
                        new
                        {
                            BookId = 21,
                            Amount = 1,
                            LoanId = 22
                        },
                        new
                        {
                            BookId = 22,
                            Amount = 5,
                            LoanId = 11
                        },
                        new
                        {
                            BookId = 23,
                            Amount = 4,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 24,
                            Amount = 3,
                            LoanId = 27
                        },
                        new
                        {
                            BookId = 25,
                            Amount = 5,
                            LoanId = 16
                        },
                        new
                        {
                            BookId = 26,
                            Amount = 5,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 27,
                            Amount = 1,
                            LoanId = 35
                        },
                        new
                        {
                            BookId = 28,
                            Amount = 4,
                            LoanId = 27
                        },
                        new
                        {
                            BookId = 29,
                            Amount = 2,
                            LoanId = 15
                        },
                        new
                        {
                            BookId = 30,
                            Amount = 5,
                            LoanId = 36
                        },
                        new
                        {
                            BookId = 31,
                            Amount = 5,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 32,
                            Amount = 2,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 33,
                            Amount = 4,
                            LoanId = 5
                        },
                        new
                        {
                            BookId = 34,
                            Amount = 1,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 35,
                            Amount = 3,
                            LoanId = 34
                        },
                        new
                        {
                            BookId = 36,
                            Amount = 3,
                            LoanId = 39
                        },
                        new
                        {
                            BookId = 37,
                            Amount = 4,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 38,
                            Amount = 2,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 39,
                            Amount = 5,
                            LoanId = 24
                        },
                        new
                        {
                            BookId = 40,
                            Amount = 4,
                            LoanId = 20
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Reilly Trail 141",
                            FullName = "magni Schroeder",
                            LoanId = 21,
                            Phone = "536-588-6085"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Langworth Hill 937",
                            FullName = "incidunt Haag",
                            LoanId = 8,
                            Phone = "804-247-1722"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Ondricka Mountains 949",
                            FullName = "voluptas Turcotte",
                            LoanId = 39,
                            Phone = "749-706-9165"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Hamill Junctions 1051",
                            FullName = "non Roberts",
                            LoanId = 13,
                            Phone = "676-492-7512"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Marks Meadows 2358",
                            FullName = "ipsam Ratke",
                            LoanId = 26,
                            Phone = "308-337-8055"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Johnson Rapid 1965",
                            FullName = "et Parker",
                            LoanId = 34,
                            Phone = "668-362-6125"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Torp Rest 1719",
                            FullName = "cumque Predovic",
                            LoanId = 26,
                            Phone = "850-846-9228"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "O'Connell Club 1031",
                            FullName = "necessitatibus Kerluke",
                            LoanId = 33,
                            Phone = "695-623-4867"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Myrtle Valley 1232",
                            FullName = "reprehenderit Harvey",
                            LoanId = 34,
                            Phone = "492-456-4279"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Dewayne Pass 939",
                            FullName = "est Heidenreich",
                            LoanId = 10,
                            Phone = "696-390-8290"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Goodwin Ports 1238",
                            FullName = "sint Walter",
                            LoanId = 29,
                            Phone = "604-426-9034"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Langworth Place 2045",
                            FullName = "laboriosam Jacobi",
                            LoanId = 23,
                            Phone = "557-958-1846"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Maeve Grove 1164",
                            FullName = "quia Pouros",
                            LoanId = 22,
                            Phone = "370-783-1180"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Queenie Skyway 975",
                            FullName = "esse McCullough",
                            LoanId = 22,
                            Phone = "480-883-3262"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Cullen Ford 2348",
                            FullName = "repellat Howell",
                            LoanId = 29,
                            Phone = "502-411-3247"
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "Anissa Junction 1586",
                            FullName = "voluptatem Kohler",
                            LoanId = 34,
                            Phone = "863-644-8151"
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "Forrest Shores 126",
                            FullName = "vero Trantow",
                            LoanId = 27,
                            Phone = "217-328-9196"
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "Schuppe Radial 1662",
                            FullName = "quis O'Keefe",
                            LoanId = 18,
                            Phone = "219-941-0407"
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "Jamel Valleys 1978",
                            FullName = "deleniti Hilpert",
                            LoanId = 22,
                            Phone = "296-352-8377"
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "McKenzie Mountain 2307",
                            FullName = "maiores Huel",
                            LoanId = 35,
                            Phone = "200-662-3809"
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "Rosalia Turnpike 729",
                            FullName = "deleniti Boehm",
                            LoanId = 5,
                            Phone = "376-426-3384"
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "Gus Hills 545",
                            FullName = "expedita Heidenreich",
                            LoanId = 25,
                            Phone = "404-918-5608"
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "Calista Islands 88",
                            FullName = "sint Klocko",
                            LoanId = 23,
                            Phone = "640-205-1086"
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "Patsy Divide 971",
                            FullName = "tempora Larkin",
                            LoanId = 8,
                            Phone = "747-233-8410"
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "Pouros Roads 668",
                            FullName = "qui Welch",
                            LoanId = 31,
                            Phone = "299-720-2455"
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "Mohr Curve 1643",
                            FullName = "voluptas Schuppe",
                            LoanId = 5,
                            Phone = "550-773-0646"
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "Morissette Ports 1227",
                            FullName = "provident Funk",
                            LoanId = 29,
                            Phone = "711-594-3519"
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "Gottlieb Vista 110",
                            FullName = "voluptas Mante",
                            LoanId = 4,
                            Phone = "383-925-0423"
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "Kling Greens 1875",
                            FullName = "velit Morar",
                            LoanId = 11,
                            Phone = "294-304-1145"
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "Tatyana Creek 532",
                            FullName = "sit Bruen",
                            LoanId = 27,
                            Phone = "591-369-7731"
                        },
                        new
                        {
                            CustomerId = 31,
                            Address = "Aurelia Crescent 2268",
                            FullName = "et Cassin",
                            LoanId = 2,
                            Phone = "788-832-9548"
                        },
                        new
                        {
                            CustomerId = 32,
                            Address = "O'Conner Mews 401",
                            FullName = "atque Keeling",
                            LoanId = 10,
                            Phone = "816-305-8464"
                        },
                        new
                        {
                            CustomerId = 33,
                            Address = "Runolfsdottir Port 1294",
                            FullName = "minima Ward",
                            LoanId = 36,
                            Phone = "634-299-1094"
                        },
                        new
                        {
                            CustomerId = 34,
                            Address = "Lexus Parkways 2188",
                            FullName = "tempora Mann",
                            LoanId = 4,
                            Phone = "881-629-6914"
                        },
                        new
                        {
                            CustomerId = 35,
                            Address = "Marvin Falls 1846",
                            FullName = "possimus Beer",
                            LoanId = 22,
                            Phone = "432-595-1601"
                        },
                        new
                        {
                            CustomerId = 36,
                            Address = "Powlowski Viaduct 329",
                            FullName = "ut Christiansen",
                            LoanId = 28,
                            Phone = "684-589-6070"
                        },
                        new
                        {
                            CustomerId = 37,
                            Address = "Adams Locks 510",
                            FullName = "voluptatum Mayer",
                            LoanId = 16,
                            Phone = "729-592-3744"
                        },
                        new
                        {
                            CustomerId = 38,
                            Address = "Erdman Ville 87",
                            FullName = "nostrum Kuhlman",
                            LoanId = 7,
                            Phone = "775-430-1113"
                        },
                        new
                        {
                            CustomerId = 39,
                            Address = "Rashawn Springs 942",
                            FullName = "molestiae Funk",
                            LoanId = 29,
                            Phone = "269-928-3657"
                        },
                        new
                        {
                            CustomerId = 40,
                            Address = "Kristina Plain 271",
                            FullName = "voluptatem Little",
                            LoanId = 26,
                            Phone = "600-956-0795"
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookLoanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BookReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysToLoan")
                        .HasColumnType("int");

                    b.Property<bool?>("ReturnedInTime")
                        .HasColumnType("bit");

                    b.HasKey("LoanId");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            BookId = 18,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6373),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 2,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6734),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 3,
                            BookId = 29,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6746),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 4,
                            BookId = 35,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6754),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 5,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6759),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 6,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6765),
                            CustomerId = 12,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 7,
                            BookId = 17,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6770),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 8,
                            BookId = 8,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6776),
                            CustomerId = 38,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 9,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6782),
                            CustomerId = 34,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 10,
                            BookId = 38,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6787),
                            CustomerId = 16,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 11,
                            BookId = 25,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6793),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 12,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6798),
                            CustomerId = 5,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 13,
                            BookId = 13,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6803),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 14,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6809),
                            CustomerId = 37,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 15,
                            BookId = 13,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6814),
                            CustomerId = 37,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 16,
                            BookId = 22,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6820),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 17,
                            BookId = 15,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6825),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 18,
                            BookId = 29,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6831),
                            CustomerId = 11,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 19,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6836),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 20,
                            BookId = 7,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6842),
                            CustomerId = 19,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 21,
                            BookId = 36,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6847),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 22,
                            BookId = 31,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6852),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 23,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6857),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 24,
                            BookId = 14,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6862),
                            CustomerId = 39,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 25,
                            BookId = 25,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6867),
                            CustomerId = 34,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 26,
                            BookId = 36,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6873),
                            CustomerId = 12,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 27,
                            BookId = 3,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6879),
                            CustomerId = 29,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 28,
                            BookId = 1,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6884),
                            CustomerId = 15,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 29,
                            BookId = 36,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6889),
                            CustomerId = 31,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 30,
                            BookId = 25,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6894),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 31,
                            BookId = 34,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6900),
                            CustomerId = 5,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 32,
                            BookId = 15,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6905),
                            CustomerId = 15,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 33,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6910),
                            CustomerId = 40,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 34,
                            BookId = 40,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6915),
                            CustomerId = 11,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 35,
                            BookId = 3,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6920),
                            CustomerId = 35,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 36,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6926),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 37,
                            BookId = 2,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6931),
                            CustomerId = 34,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 38,
                            BookId = 39,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6936),
                            CustomerId = 35,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 39,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6942),
                            CustomerId = 38,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 40,
                            BookId = 38,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 29, 31, 143, DateTimeKind.Local).AddTicks(6947),
                            CustomerId = 32,
                            DaysToLoan = 30
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.HasOne("Labb1MVC_Simon.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1MVC_Simon.Models.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
