// <auto-generated />
using System;
using Labb1MVC_Simon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1MVC_Simon.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20220922070124_faker")]
    partial class faker
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Amount = 5,
                            LoanId = 24
                        },
                        new
                        {
                            BookId = 2,
                            Amount = 2,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 3,
                            Amount = 4,
                            LoanId = 25
                        },
                        new
                        {
                            BookId = 4,
                            Amount = 3,
                            LoanId = 3
                        },
                        new
                        {
                            BookId = 5,
                            Amount = 2,
                            LoanId = 1
                        },
                        new
                        {
                            BookId = 6,
                            Amount = 1,
                            LoanId = 14
                        },
                        new
                        {
                            BookId = 7,
                            Amount = 4,
                            LoanId = 35
                        },
                        new
                        {
                            BookId = 8,
                            Amount = 4,
                            LoanId = 5
                        },
                        new
                        {
                            BookId = 9,
                            Amount = 1,
                            LoanId = 10
                        },
                        new
                        {
                            BookId = 10,
                            Amount = 5,
                            LoanId = 25
                        },
                        new
                        {
                            BookId = 11,
                            Amount = 5,
                            LoanId = 8
                        },
                        new
                        {
                            BookId = 12,
                            Amount = 3,
                            LoanId = 29
                        },
                        new
                        {
                            BookId = 13,
                            Amount = 2,
                            LoanId = 23
                        },
                        new
                        {
                            BookId = 14,
                            Amount = 1,
                            LoanId = 14
                        },
                        new
                        {
                            BookId = 15,
                            Amount = 1,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 16,
                            Amount = 4,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 17,
                            Amount = 2,
                            LoanId = 22
                        },
                        new
                        {
                            BookId = 18,
                            Amount = 2,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 19,
                            Amount = 3,
                            LoanId = 25
                        },
                        new
                        {
                            BookId = 20,
                            Amount = 1,
                            LoanId = 3
                        },
                        new
                        {
                            BookId = 21,
                            Amount = 1,
                            LoanId = 39
                        },
                        new
                        {
                            BookId = 22,
                            Amount = 3,
                            LoanId = 34
                        },
                        new
                        {
                            BookId = 23,
                            Amount = 3,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 24,
                            Amount = 4,
                            LoanId = 16
                        },
                        new
                        {
                            BookId = 25,
                            Amount = 5,
                            LoanId = 11
                        },
                        new
                        {
                            BookId = 26,
                            Amount = 2,
                            LoanId = 16
                        },
                        new
                        {
                            BookId = 27,
                            Amount = 5,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 28,
                            Amount = 4,
                            LoanId = 19
                        },
                        new
                        {
                            BookId = 29,
                            Amount = 4,
                            LoanId = 14
                        },
                        new
                        {
                            BookId = 30,
                            Amount = 2,
                            LoanId = 23
                        },
                        new
                        {
                            BookId = 31,
                            Amount = 4,
                            LoanId = 35
                        },
                        new
                        {
                            BookId = 32,
                            Amount = 2,
                            LoanId = 1
                        },
                        new
                        {
                            BookId = 33,
                            Amount = 5,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 34,
                            Amount = 4,
                            LoanId = 32
                        },
                        new
                        {
                            BookId = 35,
                            Amount = 1,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 36,
                            Amount = 2,
                            LoanId = 25
                        },
                        new
                        {
                            BookId = 37,
                            Amount = 1,
                            LoanId = 1
                        },
                        new
                        {
                            BookId = 38,
                            Amount = 5,
                            LoanId = 32
                        },
                        new
                        {
                            BookId = 39,
                            Amount = 2,
                            LoanId = 20
                        },
                        new
                        {
                            BookId = 40,
                            Amount = 4,
                            LoanId = 27
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Stationsvägen 59",
                            FullName = "Cassandra Eriksson",
                            LoanId = 1,
                            Phone = "5349-36855"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Perssons Gata 9",
                            FullName = "Isaias Svensson",
                            LoanId = 27,
                            Phone = "7450-63806"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Amaris Gata 354",
                            FullName = "Michale Johansson",
                            LoanId = 15,
                            Phone = "0636-89706"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Lindseys Väg 288",
                            FullName = "Darrion Johansson",
                            LoanId = 3,
                            Phone = "5007-94836"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Florines Väg 0",
                            FullName = "Heather Eriksson",
                            LoanId = 10,
                            Phone = "4644-68688"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Kyrkovägen 83",
                            FullName = "Javon Andersson",
                            LoanId = 28,
                            Phone = "6235-38112"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Olssons Gata 6",
                            FullName = "Mavis Nilsson",
                            LoanId = 10,
                            Phone = "6763-28540"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Devens Väg 693",
                            FullName = "Diana Nilsson",
                            LoanId = 22,
                            Phone = "6063-10119"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Åkerallén 47",
                            FullName = "Pattie Persson",
                            LoanId = 3,
                            Phone = "3089-36342"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Kyrkgärdet 2",
                            FullName = "Jayde Karlsson",
                            LoanId = 29,
                            Phone = "1561-46424"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Vicentas Gata 94",
                            FullName = "Tessie Olsson",
                            LoanId = 18,
                            Phone = "3522-99176"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Övre Skolvägen 776",
                            FullName = "Neha Olsson",
                            LoanId = 11,
                            Phone = "7963-53685"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Strandallén 0",
                            FullName = "Ephraim Persson",
                            LoanId = 34,
                            Phone = "1222-38751"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Nonas Väg 6",
                            FullName = "Wilford Persson",
                            LoanId = 17,
                            Phone = "9516-41014"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Strandgatan 6",
                            FullName = "Destiny Larsson",
                            LoanId = 14,
                            Phone = "3503-63930"
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "Novas Gata 6",
                            FullName = "Reese Karlsson",
                            LoanId = 36,
                            Phone = "5388-61201"
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "Londons Väg 7",
                            FullName = "Karlee Persson",
                            LoanId = 39,
                            Phone = "0822-93859"
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "Östra Ängsgränden 549",
                            FullName = "Emmanuel Persson",
                            LoanId = 33,
                            Phone = "2920-13445"
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "Östra Villagränden 834",
                            FullName = "Murl Karlsson",
                            LoanId = 14,
                            Phone = "5758-14266"
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "Ängsvägen 91",
                            FullName = "Aryanna Svensson",
                            LoanId = 19,
                            Phone = "9606-96282"
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "Skolgatan 33",
                            FullName = "Lynn Karlsson",
                            LoanId = 3,
                            Phone = "9978-30951"
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "Östra Åkergränden 4",
                            FullName = "Zackary Olsson",
                            LoanId = 35,
                            Phone = "5812-52309"
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "Stationsallén 75",
                            FullName = "Wilburn Andersson",
                            LoanId = 39,
                            Phone = "4302-06791"
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "Larssons Gata 894",
                            FullName = "Violette Andersson",
                            LoanId = 39,
                            Phone = "7175-23025"
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "Ringgränden 6",
                            FullName = "Garfield Gustafsson",
                            LoanId = 4,
                            Phone = "9905-35222"
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "Gengärdet 830",
                            FullName = "Rosamond Johansson",
                            LoanId = 8,
                            Phone = "8073-20980"
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "Bäckallén 137",
                            FullName = "Mckenzie Andersson",
                            LoanId = 19,
                            Phone = "7186-04385"
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "Skogsgärdet 694",
                            FullName = "Jennyfer Larsson",
                            LoanId = 14,
                            Phone = "1836-84244"
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "Rays Väg 0",
                            FullName = "Aida Persson",
                            LoanId = 18,
                            Phone = "7646-51098"
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "Övre Ringgränden 1",
                            FullName = "Levi Olsson",
                            LoanId = 25,
                            Phone = "6268-24169"
                        },
                        new
                        {
                            CustomerId = 31,
                            Address = "Ulisess Väg 12",
                            FullName = "Elise Larsson",
                            LoanId = 7,
                            Phone = "9444-59163"
                        },
                        new
                        {
                            CustomerId = 32,
                            Address = "Perssons Gata 6",
                            FullName = "Marion Svensson",
                            LoanId = 32,
                            Phone = "6702-67331"
                        },
                        new
                        {
                            CustomerId = 33,
                            Address = "Västra Furugatan 0",
                            FullName = "Brianne Olsson",
                            LoanId = 32,
                            Phone = "0428-09779"
                        },
                        new
                        {
                            CustomerId = 34,
                            Address = "Camerons Väg 604",
                            FullName = "Jordyn Olsson",
                            LoanId = 16,
                            Phone = "8907-71979"
                        },
                        new
                        {
                            CustomerId = 35,
                            Address = "Frederiks Gata 94",
                            FullName = "Keshawn Nilsson",
                            LoanId = 25,
                            Phone = "2194-78514"
                        },
                        new
                        {
                            CustomerId = 36,
                            Address = "Gustafssons Gata 167",
                            FullName = "Jude Gustafsson",
                            LoanId = 36,
                            Phone = "6275-80126"
                        },
                        new
                        {
                            CustomerId = 37,
                            Address = "Kyrkogränden 9",
                            FullName = "Danyka Karlsson",
                            LoanId = 12,
                            Phone = "6610-59121"
                        },
                        new
                        {
                            CustomerId = 38,
                            Address = "Genevieves Gata 402",
                            FullName = "Uriel Persson",
                            LoanId = 30,
                            Phone = "9659-23743"
                        },
                        new
                        {
                            CustomerId = 39,
                            Address = "Pamelas Gata 65",
                            FullName = "Casimir Karlsson",
                            LoanId = 13,
                            Phone = "6406-91738"
                        },
                        new
                        {
                            CustomerId = 40,
                            Address = "Svenssons Väg 97",
                            FullName = "Alene Johansson",
                            LoanId = 6,
                            Phone = "3133-78695"
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookLoanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BookReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysToLoan")
                        .HasColumnType("int");

                    b.Property<bool?>("ReturnedInTime")
                        .HasColumnType("bit");

                    b.HasKey("LoanId");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(5950),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 2,
                            BookId = 40,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6359),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 3,
                            BookId = 2,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6370),
                            CustomerId = 34,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 4,
                            BookId = 22,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6377),
                            CustomerId = 29,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 5,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6382),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 6,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6387),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 7,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6393),
                            CustomerId = 22,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 8,
                            BookId = 18,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6398),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 9,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6403),
                            CustomerId = 22,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 10,
                            BookId = 30,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6408),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 11,
                            BookId = 22,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6414),
                            CustomerId = 38,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 12,
                            BookId = 29,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6419),
                            CustomerId = 12,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 13,
                            BookId = 17,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6424),
                            CustomerId = 39,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 14,
                            BookId = 1,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6472),
                            CustomerId = 29,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 15,
                            BookId = 25,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6478),
                            CustomerId = 2,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 16,
                            BookId = 7,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6483),
                            CustomerId = 34,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 17,
                            BookId = 19,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6488),
                            CustomerId = 10,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 18,
                            BookId = 3,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6493),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 19,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6498),
                            CustomerId = 27,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 20,
                            BookId = 37,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6504),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 21,
                            BookId = 37,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6509),
                            CustomerId = 32,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 22,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6514),
                            CustomerId = 21,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 23,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6519),
                            CustomerId = 32,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 24,
                            BookId = 32,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6524),
                            CustomerId = 16,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 25,
                            BookId = 31,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6530),
                            CustomerId = 21,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 26,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6535),
                            CustomerId = 5,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 27,
                            BookId = 11,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6540),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 28,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6545),
                            CustomerId = 8,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 29,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6550),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 30,
                            BookId = 34,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6555),
                            CustomerId = 29,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 31,
                            BookId = 3,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6561),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 32,
                            BookId = 1,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6566),
                            CustomerId = 2,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 33,
                            BookId = 7,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6571),
                            CustomerId = 15,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 34,
                            BookId = 28,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6576),
                            CustomerId = 40,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 35,
                            BookId = 17,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6581),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 36,
                            BookId = 16,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6586),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 37,
                            BookId = 17,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6592),
                            CustomerId = 12,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 38,
                            BookId = 11,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6597),
                            CustomerId = 40,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 39,
                            BookId = 11,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6602),
                            CustomerId = 34,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 40,
                            BookId = 5,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 1, 24, 155, DateTimeKind.Local).AddTicks(6606),
                            CustomerId = 3,
                            DaysToLoan = 30
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.HasOne("Labb1MVC_Simon.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1MVC_Simon.Models.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
