// <auto-generated />
using System;
using Labb1MVC_Simon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1MVC_Simon.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20220922065744_newnames")]
    partial class newnames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Amount = 3,
                            LoanId = 8
                        },
                        new
                        {
                            BookId = 2,
                            Amount = 4,
                            LoanId = 18
                        },
                        new
                        {
                            BookId = 3,
                            Amount = 2,
                            LoanId = 38
                        },
                        new
                        {
                            BookId = 4,
                            Amount = 5,
                            LoanId = 23
                        },
                        new
                        {
                            BookId = 5,
                            Amount = 1,
                            LoanId = 16
                        },
                        new
                        {
                            BookId = 6,
                            Amount = 2,
                            LoanId = 35
                        },
                        new
                        {
                            BookId = 7,
                            Amount = 1,
                            LoanId = 18
                        },
                        new
                        {
                            BookId = 8,
                            Amount = 4,
                            LoanId = 35
                        },
                        new
                        {
                            BookId = 9,
                            Amount = 5,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 10,
                            Amount = 4,
                            LoanId = 16
                        },
                        new
                        {
                            BookId = 11,
                            Amount = 2,
                            LoanId = 5
                        },
                        new
                        {
                            BookId = 12,
                            Amount = 1,
                            LoanId = 20
                        },
                        new
                        {
                            BookId = 13,
                            Amount = 4,
                            LoanId = 5
                        },
                        new
                        {
                            BookId = 14,
                            Amount = 5,
                            LoanId = 21
                        },
                        new
                        {
                            BookId = 15,
                            Amount = 3,
                            LoanId = 29
                        },
                        new
                        {
                            BookId = 16,
                            Amount = 3,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 17,
                            Amount = 4,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 18,
                            Amount = 5,
                            LoanId = 19
                        },
                        new
                        {
                            BookId = 19,
                            Amount = 1,
                            LoanId = 29
                        },
                        new
                        {
                            BookId = 20,
                            Amount = 3,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 21,
                            Amount = 5,
                            LoanId = 14
                        },
                        new
                        {
                            BookId = 22,
                            Amount = 3,
                            LoanId = 18
                        },
                        new
                        {
                            BookId = 23,
                            Amount = 3,
                            LoanId = 15
                        },
                        new
                        {
                            BookId = 24,
                            Amount = 4,
                            LoanId = 23
                        },
                        new
                        {
                            BookId = 25,
                            Amount = 1,
                            LoanId = 9
                        },
                        new
                        {
                            BookId = 26,
                            Amount = 3,
                            LoanId = 20
                        },
                        new
                        {
                            BookId = 27,
                            Amount = 4,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 28,
                            Amount = 2,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 29,
                            Amount = 4,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 30,
                            Amount = 5,
                            LoanId = 20
                        },
                        new
                        {
                            BookId = 31,
                            Amount = 3,
                            LoanId = 39
                        },
                        new
                        {
                            BookId = 32,
                            Amount = 1,
                            LoanId = 40
                        },
                        new
                        {
                            BookId = 33,
                            Amount = 3,
                            LoanId = 22
                        },
                        new
                        {
                            BookId = 34,
                            Amount = 3,
                            LoanId = 10
                        },
                        new
                        {
                            BookId = 35,
                            Amount = 3,
                            LoanId = 25
                        },
                        new
                        {
                            BookId = 36,
                            Amount = 4,
                            LoanId = 3
                        },
                        new
                        {
                            BookId = 37,
                            Amount = 5,
                            LoanId = 4
                        },
                        new
                        {
                            BookId = 38,
                            Amount = 2,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 39,
                            Amount = 2,
                            LoanId = 22
                        },
                        new
                        {
                            BookId = 40,
                            Amount = 4,
                            LoanId = 4
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Södra Strandgränden 424",
                            FullName = "Billy Svensson",
                            LoanId = 12,
                            Phone = "1620-90113"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Parkgärdet 34",
                            FullName = "Conor Svensson",
                            LoanId = 14,
                            Phone = "4118-70456"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Kyrkgränden 2",
                            FullName = "Jace Persson",
                            LoanId = 19,
                            Phone = "8065-93846"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Gengatan 693",
                            FullName = "Jermey Eriksson",
                            LoanId = 20,
                            Phone = "6243-32069"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Larssons Gata 40",
                            FullName = "Gillian Johansson",
                            LoanId = 24,
                            Phone = "6842-22573"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Larssons Gata 6",
                            FullName = "Dina Andersson",
                            LoanId = 3,
                            Phone = "7460-49397"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Villavägen 3",
                            FullName = "Oren Svensson",
                            LoanId = 13,
                            Phone = "6568-35653"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Sarinas Gata 84",
                            FullName = "Boris Karlsson",
                            LoanId = 13,
                            Phone = "4501-66815"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Olssons Väg 8",
                            FullName = "Lavinia Gustafsson",
                            LoanId = 18,
                            Phone = "2520-12683"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Olssons Gata 212",
                            FullName = "Frank Nilsson",
                            LoanId = 9,
                            Phone = "8209-91439"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Luzs Gata 0",
                            FullName = "Kiana Andersson",
                            LoanId = 20,
                            Phone = "2196-88945"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Erikssons Väg 224",
                            FullName = "Hailie Nilsson",
                            LoanId = 20,
                            Phone = "2902-34171"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Bäckallén 272",
                            FullName = "Kaleigh Larsson",
                            LoanId = 15,
                            Phone = "0653-66468"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Ginas Väg 14",
                            FullName = "Randy Larsson",
                            LoanId = 14,
                            Phone = "8866-97885"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Furuvägen 24",
                            FullName = "Etha Persson",
                            LoanId = 25,
                            Phone = "2604-02420"
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "Marlins Gata 9",
                            FullName = "Anissa Eriksson",
                            LoanId = 5,
                            Phone = "7786-35600"
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "Västra Trädgårdgatan 986",
                            FullName = "Lisette Olsson",
                            LoanId = 23,
                            Phone = "3283-28483"
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "Thelmas Väg 929",
                            FullName = "Orin Svensson",
                            LoanId = 7,
                            Phone = "1376-17165"
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "Margots Väg 205",
                            FullName = "Mazie Svensson",
                            LoanId = 11,
                            Phone = "5504-87797"
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "Övre Ekgatan 999",
                            FullName = "Demetrius Olsson",
                            LoanId = 2,
                            Phone = "5187-19658"
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "Storallén 8",
                            FullName = "Josh Karlsson",
                            LoanId = 21,
                            Phone = "4898-16196"
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "Larssons Väg 1",
                            FullName = "Leilani Johansson",
                            LoanId = 11,
                            Phone = "1677-57173"
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "Stanleys Väg 3",
                            FullName = "Stevie Andersson",
                            LoanId = 11,
                            Phone = "8148-49865"
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "Larssons Gata 8",
                            FullName = "Barbara Olsson",
                            LoanId = 27,
                            Phone = "3419-50672"
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "Ringgatan 1",
                            FullName = "Cecile Nilsson",
                            LoanId = 12,
                            Phone = "4347-04264"
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "Undre Kyrkogärdet 202",
                            FullName = "Yessenia Nilsson",
                            LoanId = 17,
                            Phone = "1259-18743"
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "Övre Skolvägen 26",
                            FullName = "Michelle Karlsson",
                            LoanId = 9,
                            Phone = "5134-65173"
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "Monserrats Gata 063",
                            FullName = "Kali Olsson",
                            LoanId = 11,
                            Phone = "9058-29818"
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "Södra Åkergatan 27",
                            FullName = "Jade Olsson",
                            LoanId = 9,
                            Phone = "1339-43263"
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "Rocios Väg 666",
                            FullName = "Mallory Persson",
                            LoanId = 26,
                            Phone = "4741-13381"
                        },
                        new
                        {
                            CustomerId = 31,
                            Address = "Västra Industrivägen 831",
                            FullName = "Hilda Johansson",
                            LoanId = 21,
                            Phone = "1443-46089"
                        },
                        new
                        {
                            CustomerId = 32,
                            Address = "Västra Villagatan 82",
                            FullName = "Florian Andersson",
                            LoanId = 5,
                            Phone = "3006-95389"
                        },
                        new
                        {
                            CustomerId = 33,
                            Address = "Övre Storvägen 88",
                            FullName = "Alexzander Nilsson",
                            LoanId = 11,
                            Phone = "0807-16867"
                        },
                        new
                        {
                            CustomerId = 34,
                            Address = "Nygränden 24",
                            FullName = "Viva Larsson",
                            LoanId = 22,
                            Phone = "2307-75297"
                        },
                        new
                        {
                            CustomerId = 35,
                            Address = "Larssons Väg 9",
                            FullName = "Juana Olsson",
                            LoanId = 13,
                            Phone = "6247-41195"
                        },
                        new
                        {
                            CustomerId = 36,
                            Address = "Ekgatan 119",
                            FullName = "Eliane Gustafsson",
                            LoanId = 22,
                            Phone = "7256-59513"
                        },
                        new
                        {
                            CustomerId = 37,
                            Address = "Kyrkogärdet 64",
                            FullName = "Eveline Gustafsson",
                            LoanId = 14,
                            Phone = "8354-48133"
                        },
                        new
                        {
                            CustomerId = 38,
                            Address = "Norra Trädgårdvägen 2",
                            FullName = "Maiya Karlsson",
                            LoanId = 23,
                            Phone = "8708-84938"
                        },
                        new
                        {
                            CustomerId = 39,
                            Address = "Gustafssons Väg 6",
                            FullName = "Kurtis Persson",
                            LoanId = 14,
                            Phone = "9802-26834"
                        },
                        new
                        {
                            CustomerId = 40,
                            Address = "Södra Gengatan 915",
                            FullName = "Moises Andersson",
                            LoanId = 30,
                            Phone = "7746-05489"
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookLoanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BookReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysToLoan")
                        .HasColumnType("int");

                    b.Property<bool?>("ReturnedInTime")
                        .HasColumnType("bit");

                    b.HasKey("LoanId");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4487),
                            CustomerId = 10,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 2,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4763),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 3,
                            BookId = 28,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4774),
                            CustomerId = 21,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 4,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4781),
                            CustomerId = 26,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 5,
                            BookId = 5,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4786),
                            CustomerId = 22,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 6,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4791),
                            CustomerId = 16,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 7,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4796),
                            CustomerId = 25,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 8,
                            BookId = 2,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4801),
                            CustomerId = 14,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 9,
                            BookId = 18,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4806),
                            CustomerId = 10,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 10,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4811),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 11,
                            BookId = 3,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4816),
                            CustomerId = 6,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 12,
                            BookId = 1,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4821),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 13,
                            BookId = 5,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4825),
                            CustomerId = 27,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 14,
                            BookId = 8,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4831),
                            CustomerId = 14,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 15,
                            BookId = 16,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4835),
                            CustomerId = 29,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 16,
                            BookId = 4,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4840),
                            CustomerId = 11,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 17,
                            BookId = 11,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4845),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 18,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4850),
                            CustomerId = 22,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 19,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4855),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 20,
                            BookId = 13,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4860),
                            CustomerId = 16,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 21,
                            BookId = 2,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4865),
                            CustomerId = 6,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 22,
                            BookId = 19,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4870),
                            CustomerId = 1,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 23,
                            BookId = 25,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4874),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 24,
                            BookId = 7,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4879),
                            CustomerId = 16,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 25,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4884),
                            CustomerId = 29,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 26,
                            BookId = 15,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4889),
                            CustomerId = 23,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 27,
                            BookId = 7,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4900),
                            CustomerId = 20,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 28,
                            BookId = 7,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4905),
                            CustomerId = 10,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 29,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4910),
                            CustomerId = 1,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 30,
                            BookId = 9,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4915),
                            CustomerId = 23,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 31,
                            BookId = 16,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4920),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 32,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4924),
                            CustomerId = 14,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 33,
                            BookId = 4,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4929),
                            CustomerId = 14,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 34,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4934),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 35,
                            BookId = 11,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4939),
                            CustomerId = 5,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 36,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4944),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 37,
                            BookId = 9,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4949),
                            CustomerId = 6,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 38,
                            BookId = 3,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4954),
                            CustomerId = 27,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 39,
                            BookId = 3,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4958),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 40,
                            BookId = 30,
                            BookLoanDate = new DateTime(2022, 9, 22, 8, 57, 44, 470, DateTimeKind.Local).AddTicks(4963),
                            CustomerId = 21,
                            DaysToLoan = 30
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.HasOne("Labb1MVC_Simon.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1MVC_Simon.Models.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
