// <auto-generated />
using System;
using Labb1MVC_Simon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1MVC_Simon.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20220922072517_usernames")]
    partial class usernames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Amount = 3,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 2,
                            Amount = 5,
                            LoanId = 24
                        },
                        new
                        {
                            BookId = 3,
                            Amount = 2,
                            LoanId = 13
                        },
                        new
                        {
                            BookId = 4,
                            Amount = 1,
                            LoanId = 34
                        },
                        new
                        {
                            BookId = 5,
                            Amount = 5,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 6,
                            Amount = 5,
                            LoanId = 34
                        },
                        new
                        {
                            BookId = 7,
                            Amount = 1,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 8,
                            Amount = 5,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 9,
                            Amount = 1,
                            LoanId = 2
                        },
                        new
                        {
                            BookId = 10,
                            Amount = 2,
                            LoanId = 11
                        },
                        new
                        {
                            BookId = 11,
                            Amount = 2,
                            LoanId = 6
                        },
                        new
                        {
                            BookId = 12,
                            Amount = 2,
                            LoanId = 31
                        },
                        new
                        {
                            BookId = 13,
                            Amount = 1,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 14,
                            Amount = 4,
                            LoanId = 39
                        },
                        new
                        {
                            BookId = 15,
                            Amount = 5,
                            LoanId = 27
                        },
                        new
                        {
                            BookId = 16,
                            Amount = 5,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 17,
                            Amount = 4,
                            LoanId = 4
                        },
                        new
                        {
                            BookId = 18,
                            Amount = 3,
                            LoanId = 36
                        },
                        new
                        {
                            BookId = 19,
                            Amount = 4,
                            LoanId = 16
                        },
                        new
                        {
                            BookId = 20,
                            Amount = 1,
                            LoanId = 14
                        },
                        new
                        {
                            BookId = 21,
                            Amount = 3,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 22,
                            Amount = 4,
                            LoanId = 3
                        },
                        new
                        {
                            BookId = 23,
                            Amount = 4,
                            LoanId = 13
                        },
                        new
                        {
                            BookId = 24,
                            Amount = 4,
                            LoanId = 39
                        },
                        new
                        {
                            BookId = 25,
                            Amount = 2,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 26,
                            Amount = 4,
                            LoanId = 24
                        },
                        new
                        {
                            BookId = 27,
                            Amount = 4,
                            LoanId = 17
                        },
                        new
                        {
                            BookId = 28,
                            Amount = 3,
                            LoanId = 10
                        },
                        new
                        {
                            BookId = 29,
                            Amount = 2,
                            LoanId = 13
                        },
                        new
                        {
                            BookId = 30,
                            Amount = 1,
                            LoanId = 14
                        },
                        new
                        {
                            BookId = 31,
                            Amount = 1,
                            LoanId = 9
                        },
                        new
                        {
                            BookId = 32,
                            Amount = 2,
                            LoanId = 26
                        },
                        new
                        {
                            BookId = 33,
                            Amount = 4,
                            LoanId = 24
                        },
                        new
                        {
                            BookId = 34,
                            Amount = 5,
                            LoanId = 22
                        },
                        new
                        {
                            BookId = 35,
                            Amount = 4,
                            LoanId = 27
                        },
                        new
                        {
                            BookId = 36,
                            Amount = 4,
                            LoanId = 15
                        },
                        new
                        {
                            BookId = 37,
                            Amount = 1,
                            LoanId = 35
                        },
                        new
                        {
                            BookId = 38,
                            Amount = 5,
                            LoanId = 26
                        },
                        new
                        {
                            BookId = 39,
                            Amount = 2,
                            LoanId = 4
                        },
                        new
                        {
                            BookId = 40,
                            Amount = 4,
                            LoanId = 35
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Nikolaus Trail2197",
                            FullName = "pixel Friesen",
                            LoanId = 13,
                            Phone = "940-314-3628"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Rau Mountains1235",
                            FullName = "bandwidth Ankunding",
                            LoanId = 30,
                            Phone = "977-587-8238"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Crist Island152",
                            FullName = "firewall Bogisich",
                            LoanId = 2,
                            Phone = "302-224-2691"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Cheyanne Course714",
                            FullName = "transmitter Roberts",
                            LoanId = 24,
                            Phone = "931-592-2724"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Kozey Drive2211",
                            FullName = "monitor Cummings",
                            LoanId = 9,
                            Phone = "541-246-5076"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Dora Causeway1688",
                            FullName = "matrix Satterfield",
                            LoanId = 38,
                            Phone = "892-584-0939"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Frederique Villages358",
                            FullName = "firewall Schimmel",
                            LoanId = 4,
                            Phone = "889-801-8985"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Owen Club1035",
                            FullName = "monitor Bechtelar",
                            LoanId = 26,
                            Phone = "452-657-9774"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Berge Springs1951",
                            FullName = "monitor Nader",
                            LoanId = 21,
                            Phone = "978-254-0023"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Baumbach Island1097",
                            FullName = "application Corkery",
                            LoanId = 37,
                            Phone = "847-409-7321"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Crooks Road21",
                            FullName = "program Huel",
                            LoanId = 37,
                            Phone = "522-796-8734"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Volkman Oval2204",
                            FullName = "port Kiehn",
                            LoanId = 10,
                            Phone = "840-777-1244"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Hodkiewicz Meadow2197",
                            FullName = "alarm King",
                            LoanId = 8,
                            Phone = "454-555-5545"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Ora Branch56",
                            FullName = "system Hessel",
                            LoanId = 13,
                            Phone = "754-269-4554"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Roselyn Ville2267",
                            FullName = "protocol Flatley",
                            LoanId = 4,
                            Phone = "605-353-0822"
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "Predovic Mountain1309",
                            FullName = "sensor Abernathy",
                            LoanId = 18,
                            Phone = "444-964-9953"
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "Tracey Burg2085",
                            FullName = "circuit Donnelly",
                            LoanId = 4,
                            Phone = "404-594-6229"
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "Weimann Point488",
                            FullName = "bus Ritchie",
                            LoanId = 3,
                            Phone = "644-777-6124"
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "Beatty Curve502",
                            FullName = "capacitor Leuschke",
                            LoanId = 12,
                            Phone = "253-684-6405"
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "Jewell Ranch811",
                            FullName = "bus Mertz",
                            LoanId = 4,
                            Phone = "358-296-4543"
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "Camren Route436",
                            FullName = "application Tremblay",
                            LoanId = 18,
                            Phone = "926-661-9995"
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "Cristopher Groves2322",
                            FullName = "circuit Lubowitz",
                            LoanId = 40,
                            Phone = "876-590-8009"
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "Raymundo Stream23",
                            FullName = "system Conn",
                            LoanId = 15,
                            Phone = "890-704-7710"
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "Borer Streets583",
                            FullName = "interface Bradtke",
                            LoanId = 14,
                            Phone = "742-878-2084"
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "Gutkowski Lakes71",
                            FullName = "interface Emmerich",
                            LoanId = 18,
                            Phone = "607-468-5910"
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "Evan Crescent168",
                            FullName = "capacitor Kshlerin",
                            LoanId = 27,
                            Phone = "412-958-3752"
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "Arnold Plains372",
                            FullName = "program Langworth",
                            LoanId = 27,
                            Phone = "725-296-1864"
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "Heather Crossroad429",
                            FullName = "interface Hammes",
                            LoanId = 33,
                            Phone = "289-819-7378"
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "Braden Tunnel1852",
                            FullName = "protocol Volkman",
                            LoanId = 18,
                            Phone = "502-423-3924"
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "Theo Brooks1087",
                            FullName = "bandwidth Borer",
                            LoanId = 17,
                            Phone = "960-548-1966"
                        },
                        new
                        {
                            CustomerId = 31,
                            Address = "Clark Shore1855",
                            FullName = "bandwidth Waters",
                            LoanId = 28,
                            Phone = "869-896-8989"
                        },
                        new
                        {
                            CustomerId = 32,
                            Address = "Hagenes Radial1435",
                            FullName = "hard drive Kerluke",
                            LoanId = 4,
                            Phone = "431-466-3486"
                        },
                        new
                        {
                            CustomerId = 33,
                            Address = "Leola Vista261",
                            FullName = "system Swaniawski",
                            LoanId = 33,
                            Phone = "889-531-5113"
                        },
                        new
                        {
                            CustomerId = 34,
                            Address = "Jadon Harbor363",
                            FullName = "system Veum",
                            LoanId = 2,
                            Phone = "979-288-7565"
                        },
                        new
                        {
                            CustomerId = 35,
                            Address = "Hirthe Stravenue1782",
                            FullName = "driver Dach",
                            LoanId = 30,
                            Phone = "344-276-0261"
                        },
                        new
                        {
                            CustomerId = 36,
                            Address = "Sipes Dale1859",
                            FullName = "transmitter Kris",
                            LoanId = 16,
                            Phone = "672-727-5013"
                        },
                        new
                        {
                            CustomerId = 37,
                            Address = "Gibson Village1786",
                            FullName = "system Johnson",
                            LoanId = 26,
                            Phone = "392-446-3498"
                        },
                        new
                        {
                            CustomerId = 38,
                            Address = "Mina Way765",
                            FullName = "panel Abernathy",
                            LoanId = 7,
                            Phone = "366-262-7986"
                        },
                        new
                        {
                            CustomerId = 39,
                            Address = "Gail Drive691",
                            FullName = "hard drive Schneider",
                            LoanId = 30,
                            Phone = "824-481-6353"
                        },
                        new
                        {
                            CustomerId = 40,
                            Address = "Hackett Light1317",
                            FullName = "port Herman",
                            LoanId = 25,
                            Phone = "951-821-4271"
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookLoanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BookReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysToLoan")
                        .HasColumnType("int");

                    b.Property<bool?>("ReturnedInTime")
                        .HasColumnType("bit");

                    b.HasKey("LoanId");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            BookId = 13,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(801),
                            CustomerId = 35,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 2,
                            BookId = 36,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1145),
                            CustomerId = 23,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 3,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1159),
                            CustomerId = 8,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 4,
                            BookId = 31,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1165),
                            CustomerId = 5,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 5,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1171),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 6,
                            BookId = 8,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1176),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 7,
                            BookId = 37,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1182),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 8,
                            BookId = 31,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1187),
                            CustomerId = 5,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 9,
                            BookId = 28,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1193),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 10,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1239),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 11,
                            BookId = 19,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1247),
                            CustomerId = 32,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 12,
                            BookId = 38,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1253),
                            CustomerId = 27,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 13,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1258),
                            CustomerId = 14,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 14,
                            BookId = 9,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1264),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 15,
                            BookId = 39,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1269),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 16,
                            BookId = 31,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1274),
                            CustomerId = 25,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 17,
                            BookId = 15,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1279),
                            CustomerId = 33,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 18,
                            BookId = 40,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1285),
                            CustomerId = 14,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 19,
                            BookId = 11,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1290),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 20,
                            BookId = 14,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1296),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 21,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1301),
                            CustomerId = 34,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 22,
                            BookId = 26,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1306),
                            CustomerId = 14,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 23,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1312),
                            CustomerId = 29,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 24,
                            BookId = 5,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1318),
                            CustomerId = 6,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 25,
                            BookId = 17,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1323),
                            CustomerId = 2,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 26,
                            BookId = 14,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1328),
                            CustomerId = 15,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 27,
                            BookId = 4,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1334),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 28,
                            BookId = 14,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1339),
                            CustomerId = 34,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 29,
                            BookId = 35,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1344),
                            CustomerId = 35,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 30,
                            BookId = 38,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1350),
                            CustomerId = 27,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 31,
                            BookId = 34,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1355),
                            CustomerId = 15,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 32,
                            BookId = 8,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1361),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 33,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1366),
                            CustomerId = 37,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 34,
                            BookId = 38,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1372),
                            CustomerId = 26,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 35,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1377),
                            CustomerId = 20,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 36,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1382),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 37,
                            BookId = 1,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1387),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 38,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1393),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 39,
                            BookId = 5,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1398),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 40,
                            BookId = 11,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 25, 16, 758, DateTimeKind.Local).AddTicks(1403),
                            CustomerId = 16,
                            DaysToLoan = 30
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.HasOne("Labb1MVC_Simon.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1MVC_Simon.Models.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
