// <auto-generated />
using System;
using Labb1MVC_Simon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1MVC_Simon.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20220922104547_avatar")]
    partial class avatar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Amount = 1,
                            LoanId = 21
                        },
                        new
                        {
                            BookId = 2,
                            Amount = 5,
                            LoanId = 17
                        },
                        new
                        {
                            BookId = 3,
                            Amount = 4,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 4,
                            Amount = 2,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 5,
                            Amount = 4,
                            LoanId = 31
                        },
                        new
                        {
                            BookId = 6,
                            Amount = 1,
                            LoanId = 27
                        },
                        new
                        {
                            BookId = 7,
                            Amount = 1,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 8,
                            Amount = 4,
                            LoanId = 34
                        },
                        new
                        {
                            BookId = 9,
                            Amount = 5,
                            LoanId = 1
                        },
                        new
                        {
                            BookId = 10,
                            Amount = 4,
                            LoanId = 10
                        },
                        new
                        {
                            BookId = 11,
                            Amount = 3,
                            LoanId = 16
                        },
                        new
                        {
                            BookId = 12,
                            Amount = 3,
                            LoanId = 8
                        },
                        new
                        {
                            BookId = 13,
                            Amount = 3,
                            LoanId = 40
                        },
                        new
                        {
                            BookId = 14,
                            Amount = 4,
                            LoanId = 5
                        },
                        new
                        {
                            BookId = 15,
                            Amount = 5,
                            LoanId = 35
                        },
                        new
                        {
                            BookId = 16,
                            Amount = 5,
                            LoanId = 6
                        },
                        new
                        {
                            BookId = 17,
                            Amount = 1,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 18,
                            Amount = 2,
                            LoanId = 4
                        },
                        new
                        {
                            BookId = 19,
                            Amount = 1,
                            LoanId = 32
                        },
                        new
                        {
                            BookId = 20,
                            Amount = 4,
                            LoanId = 15
                        },
                        new
                        {
                            BookId = 21,
                            Amount = 4,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 22,
                            Amount = 3,
                            LoanId = 13
                        },
                        new
                        {
                            BookId = 23,
                            Amount = 5,
                            LoanId = 8
                        },
                        new
                        {
                            BookId = 24,
                            Amount = 4,
                            LoanId = 2
                        },
                        new
                        {
                            BookId = 25,
                            Amount = 4,
                            LoanId = 6
                        },
                        new
                        {
                            BookId = 26,
                            Amount = 3,
                            LoanId = 32
                        },
                        new
                        {
                            BookId = 27,
                            Amount = 5,
                            LoanId = 5
                        },
                        new
                        {
                            BookId = 28,
                            Amount = 5,
                            LoanId = 9
                        },
                        new
                        {
                            BookId = 29,
                            Amount = 3,
                            LoanId = 16
                        },
                        new
                        {
                            BookId = 30,
                            Amount = 1,
                            LoanId = 10
                        },
                        new
                        {
                            BookId = 31,
                            Amount = 2,
                            LoanId = 13
                        },
                        new
                        {
                            BookId = 32,
                            Amount = 4,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 33,
                            Amount = 3,
                            LoanId = 2
                        },
                        new
                        {
                            BookId = 34,
                            Amount = 2,
                            LoanId = 2
                        },
                        new
                        {
                            BookId = 35,
                            Amount = 1,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 36,
                            Amount = 4,
                            LoanId = 24
                        },
                        new
                        {
                            BookId = 37,
                            Amount = 1,
                            LoanId = 12
                        },
                        new
                        {
                            BookId = 38,
                            Amount = 3,
                            LoanId = 38
                        },
                        new
                        {
                            BookId = 39,
                            Amount = 5,
                            LoanId = 9
                        },
                        new
                        {
                            BookId = 40,
                            Amount = 3,
                            LoanId = 35
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Koelpin Crest 2323",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1030.jpg",
                            FullName = "Robb Pollich",
                            LoanId = 10,
                            Phone = "855-867-3773"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Alanis Estate 562",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/934.jpg",
                            FullName = "Kendrick Schmidt",
                            LoanId = 26,
                            Phone = "754-762-7955"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Hackett Burg 1728",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/768.jpg",
                            FullName = "Alfreda Herman",
                            LoanId = 32,
                            Phone = "743-422-7786"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Annetta Shores 1309",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/969.jpg",
                            FullName = "Josianne Sauer",
                            LoanId = 19,
                            Phone = "918-216-5073"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Marcus Light 326",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/847.jpg",
                            FullName = "Neil Torphy",
                            LoanId = 14,
                            Phone = "241-851-2829"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Padberg Highway 2055",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/362.jpg",
                            FullName = "Kassandra Kris",
                            LoanId = 23,
                            Phone = "733-599-9423"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Pollich Pike 1245",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1105.jpg",
                            FullName = "Consuelo Runolfsson",
                            LoanId = 11,
                            Phone = "263-778-9800"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Barton Stream 1933",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/912.jpg",
                            FullName = "Clemens Kohler",
                            LoanId = 32,
                            Phone = "257-371-0204"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Lynch Wall 2082",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/376.jpg",
                            FullName = "Riley Shields",
                            LoanId = 15,
                            Phone = "350-851-0442"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Bechtelar Mission 1508",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/274.jpg",
                            FullName = "Curt Schoen",
                            LoanId = 26,
                            Phone = "487-597-1357"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Rolfson Plaza 886",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/457.jpg",
                            FullName = "Armand Rosenbaum",
                            LoanId = 40,
                            Phone = "992-281-4233"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Tremblay Plaza 1335",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/239.jpg",
                            FullName = "Erick MacGyver",
                            LoanId = 30,
                            Phone = "424-336-7916"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Santino Via 1687",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/387.jpg",
                            FullName = "Kayden Schmitt",
                            LoanId = 21,
                            Phone = "218-941-2928"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Lilliana Rue 240",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1074.jpg",
                            FullName = "Lexus Rutherford",
                            LoanId = 18,
                            Phone = "544-258-1071"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Walton Locks 1350",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1248.jpg",
                            FullName = "Kurt Bartoletti",
                            LoanId = 40,
                            Phone = "992-791-4022"
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "Green Station 1170",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/80.jpg",
                            FullName = "Concepcion Feest",
                            LoanId = 11,
                            Phone = "462-531-7180"
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "Ettie Crossing 471",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1015.jpg",
                            FullName = "Malvina Connelly",
                            LoanId = 9,
                            Phone = "331-859-7302"
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "Hattie Lights 974",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/904.jpg",
                            FullName = "Rita Lowe",
                            LoanId = 4,
                            Phone = "678-343-2323"
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "Luettgen Viaduct 329",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/916.jpg",
                            FullName = "Elvera Larson",
                            LoanId = 10,
                            Phone = "455-800-8107"
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "Roy Burgs 607",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/648.jpg",
                            FullName = "Beth Hamill",
                            LoanId = 22,
                            Phone = "498-270-6025"
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "Raymundo Rest 35",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/971.jpg",
                            FullName = "Maci Lubowitz",
                            LoanId = 9,
                            Phone = "498-793-4071"
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "Amaya Summit 2044",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/69.jpg",
                            FullName = "Stephanie Kilback",
                            LoanId = 28,
                            Phone = "504-307-1353"
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "West Burgs 63",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/143.jpg",
                            FullName = "Meghan White",
                            LoanId = 9,
                            Phone = "878-657-3359"
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "Kiarra Forks 1931",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/389.jpg",
                            FullName = "Everett Boyle",
                            LoanId = 16,
                            Phone = "783-467-1515"
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "Miller Springs 34",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/555.jpg",
                            FullName = "Skye Osinski",
                            LoanId = 10,
                            Phone = "386-521-6231"
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "Thiel Manor 2006",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/388.jpg",
                            FullName = "Precious Daniel",
                            LoanId = 24,
                            Phone = "757-780-8325"
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "Purdy Hollow 591",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/345.jpg",
                            FullName = "Bettie Wiza",
                            LoanId = 39,
                            Phone = "327-719-8917"
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "Huels Knoll 341",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/901.jpg",
                            FullName = "Berry Turcotte",
                            LoanId = 26,
                            Phone = "878-530-4094"
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "Jarred Mountains 1857",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/623.jpg",
                            FullName = "Leann MacGyver",
                            LoanId = 40,
                            Phone = "945-623-5556"
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "Rasheed Isle 1641",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/765.jpg",
                            FullName = "Dannie Brakus",
                            LoanId = 23,
                            Phone = "523-951-2184"
                        },
                        new
                        {
                            CustomerId = 31,
                            Address = "Hammes Rue 1477",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/25.jpg",
                            FullName = "Remington Stanton",
                            LoanId = 29,
                            Phone = "343-674-8092"
                        },
                        new
                        {
                            CustomerId = 32,
                            Address = "Jaydon Shoal 2105",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/398.jpg",
                            FullName = "Kip Farrell",
                            LoanId = 3,
                            Phone = "669-371-5535"
                        },
                        new
                        {
                            CustomerId = 33,
                            Address = "Cole Ford 130",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/88.jpg",
                            FullName = "Nelle Bergstrom",
                            LoanId = 36,
                            Phone = "379-931-5190"
                        },
                        new
                        {
                            CustomerId = 34,
                            Address = "Candice Crossing 2393",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/457.jpg",
                            FullName = "Samir D'Amore",
                            LoanId = 8,
                            Phone = "952-557-5775"
                        },
                        new
                        {
                            CustomerId = 35,
                            Address = "Charity Shoals 1419",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/772.jpg",
                            FullName = "Ruth Lynch",
                            LoanId = 14,
                            Phone = "541-713-2996"
                        },
                        new
                        {
                            CustomerId = 36,
                            Address = "Margaret Centers 300",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/653.jpg",
                            FullName = "Jaydon Batz",
                            LoanId = 5,
                            Phone = "627-636-3500"
                        },
                        new
                        {
                            CustomerId = 37,
                            Address = "Mireya Stream 2080",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1149.jpg",
                            FullName = "Gillian Volkman",
                            LoanId = 4,
                            Phone = "496-531-7952"
                        },
                        new
                        {
                            CustomerId = 38,
                            Address = "Henderson Land 2420",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1168.jpg",
                            FullName = "Katheryn McClure",
                            LoanId = 9,
                            Phone = "867-792-5421"
                        },
                        new
                        {
                            CustomerId = 39,
                            Address = "Guiseppe Harbors 322",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/567.jpg",
                            FullName = "Adolph Goyette",
                            LoanId = 11,
                            Phone = "468-597-8798"
                        },
                        new
                        {
                            CustomerId = 40,
                            Address = "Hollie Stream 239",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/172.jpg",
                            FullName = "Helen Boyer",
                            LoanId = 30,
                            Phone = "244-666-9073"
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookLoanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BookReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysToLoan")
                        .HasColumnType("int");

                    b.Property<bool?>("ReturnedInTime")
                        .HasColumnType("bit");

                    b.HasKey("LoanId");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            BookId = 18,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4186),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 2,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4499),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 3,
                            BookId = 22,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4512),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 4,
                            BookId = 13,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4518),
                            CustomerId = 35,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 5,
                            BookId = 34,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4523),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 6,
                            BookId = 39,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4528),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 7,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4534),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 8,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4539),
                            CustomerId = 31,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 9,
                            BookId = 16,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4544),
                            CustomerId = 35,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 10,
                            BookId = 29,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4554),
                            CustomerId = 8,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 11,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4560),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 12,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4566),
                            CustomerId = 37,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 13,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4571),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 14,
                            BookId = 17,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4576),
                            CustomerId = 33,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 15,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4581),
                            CustomerId = 40,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 16,
                            BookId = 31,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4586),
                            CustomerId = 5,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 17,
                            BookId = 33,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4591),
                            CustomerId = 25,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 18,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4596),
                            CustomerId = 37,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 19,
                            BookId = 30,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4601),
                            CustomerId = 6,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 20,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4606),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 21,
                            BookId = 2,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4611),
                            CustomerId = 1,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 22,
                            BookId = 39,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4616),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 23,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4620),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 24,
                            BookId = 37,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4626),
                            CustomerId = 37,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 25,
                            BookId = 2,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4630),
                            CustomerId = 23,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 26,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4635),
                            CustomerId = 39,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 27,
                            BookId = 33,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4641),
                            CustomerId = 1,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 28,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4645),
                            CustomerId = 24,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 29,
                            BookId = 39,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4650),
                            CustomerId = 40,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 30,
                            BookId = 3,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4655),
                            CustomerId = 8,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 31,
                            BookId = 35,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4660),
                            CustomerId = 40,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 32,
                            BookId = 31,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4665),
                            CustomerId = 33,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 33,
                            BookId = 33,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4670),
                            CustomerId = 12,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 34,
                            BookId = 35,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4675),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 35,
                            BookId = 18,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4680),
                            CustomerId = 15,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 36,
                            BookId = 25,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4685),
                            CustomerId = 8,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 37,
                            BookId = 39,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4690),
                            CustomerId = 40,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 38,
                            BookId = 4,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4695),
                            CustomerId = 26,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 39,
                            BookId = 1,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4700),
                            CustomerId = 25,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 40,
                            BookId = 4,
                            BookLoanDate = new DateTime(2022, 9, 22, 12, 45, 47, 613, DateTimeKind.Local).AddTicks(4705),
                            CustomerId = 19,
                            DaysToLoan = 30
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.HasOne("Labb1MVC_Simon.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1MVC_Simon.Models.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
