// <auto-generated />
using System;
using Labb1MVC_Simon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1MVC_Simon.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20220922073629_names1")]
    partial class names1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Amount = 3,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 2,
                            Amount = 3,
                            LoanId = 18
                        },
                        new
                        {
                            BookId = 3,
                            Amount = 4,
                            LoanId = 1
                        },
                        new
                        {
                            BookId = 4,
                            Amount = 2,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 5,
                            Amount = 3,
                            LoanId = 17
                        },
                        new
                        {
                            BookId = 6,
                            Amount = 2,
                            LoanId = 17
                        },
                        new
                        {
                            BookId = 7,
                            Amount = 3,
                            LoanId = 5
                        },
                        new
                        {
                            BookId = 8,
                            Amount = 5,
                            LoanId = 3
                        },
                        new
                        {
                            BookId = 9,
                            Amount = 4,
                            LoanId = 6
                        },
                        new
                        {
                            BookId = 10,
                            Amount = 3,
                            LoanId = 29
                        },
                        new
                        {
                            BookId = 11,
                            Amount = 4,
                            LoanId = 23
                        },
                        new
                        {
                            BookId = 12,
                            Amount = 2,
                            LoanId = 15
                        },
                        new
                        {
                            BookId = 13,
                            Amount = 2,
                            LoanId = 3
                        },
                        new
                        {
                            BookId = 14,
                            Amount = 2,
                            LoanId = 17
                        },
                        new
                        {
                            BookId = 15,
                            Amount = 5,
                            LoanId = 6
                        },
                        new
                        {
                            BookId = 16,
                            Amount = 3,
                            LoanId = 10
                        },
                        new
                        {
                            BookId = 17,
                            Amount = 3,
                            LoanId = 3
                        },
                        new
                        {
                            BookId = 18,
                            Amount = 5,
                            LoanId = 18
                        },
                        new
                        {
                            BookId = 19,
                            Amount = 2,
                            LoanId = 6
                        },
                        new
                        {
                            BookId = 20,
                            Amount = 2,
                            LoanId = 12
                        },
                        new
                        {
                            BookId = 21,
                            Amount = 4,
                            LoanId = 3
                        },
                        new
                        {
                            BookId = 22,
                            Amount = 5,
                            LoanId = 23
                        },
                        new
                        {
                            BookId = 23,
                            Amount = 2,
                            LoanId = 11
                        },
                        new
                        {
                            BookId = 24,
                            Amount = 2,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 25,
                            Amount = 3,
                            LoanId = 22
                        },
                        new
                        {
                            BookId = 26,
                            Amount = 1,
                            LoanId = 19
                        },
                        new
                        {
                            BookId = 27,
                            Amount = 2,
                            LoanId = 2
                        },
                        new
                        {
                            BookId = 28,
                            Amount = 3,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 29,
                            Amount = 4,
                            LoanId = 23
                        },
                        new
                        {
                            BookId = 30,
                            Amount = 4,
                            LoanId = 15
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Legros Inlet 1402",
                            FullName = "Edmond Gislason",
                            LoanId = 10,
                            Phone = "999-437-4728"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Lyda Plains 2112",
                            FullName = "Janiya Monahan",
                            LoanId = 26,
                            Phone = "589-347-4268"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Ewald Trail 1521",
                            FullName = "Rolando Rohan",
                            LoanId = 13,
                            Phone = "864-538-2379"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Elise Falls 499",
                            FullName = "Jennings Krajcik",
                            LoanId = 21,
                            Phone = "987-844-4129"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Labadie Points 1673",
                            FullName = "Haylie Ryan",
                            LoanId = 24,
                            Phone = "297-526-0633"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Jessyca Path 1437",
                            FullName = "River Casper",
                            LoanId = 9,
                            Phone = "515-790-5811"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Elwyn Parkway 2181",
                            FullName = "Carlee Mertz",
                            LoanId = 5,
                            Phone = "472-657-6931"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Kutch Curve 1462",
                            FullName = "Oswald Parker",
                            LoanId = 25,
                            Phone = "911-637-9442"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Foster Shoal 1173",
                            FullName = "Rahul Hand",
                            LoanId = 9,
                            Phone = "777-753-1945"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Jordi Parkway 1893",
                            FullName = "Pattie Kiehn",
                            LoanId = 2,
                            Phone = "748-593-9181"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Jefferey Crossing 475",
                            FullName = "Myrtice Hilll",
                            LoanId = 2,
                            Phone = "851-959-0964"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Daisy Shore 940",
                            FullName = "Kaia Zieme",
                            LoanId = 23,
                            Phone = "379-511-8094"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Alize Ports 1390",
                            FullName = "Deontae Wintheiser",
                            LoanId = 26,
                            Phone = "328-786-6745"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Zena Mall 636",
                            FullName = "Marcelina Crist",
                            LoanId = 21,
                            Phone = "681-846-2478"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Schuppe Greens 733",
                            FullName = "Samir Huel",
                            LoanId = 21,
                            Phone = "726-255-9289"
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "Bergnaum Rapid 1252",
                            FullName = "Larry Denesik",
                            LoanId = 11,
                            Phone = "445-666-0751"
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "Rau Station 32",
                            FullName = "Reyes Fahey",
                            LoanId = 24,
                            Phone = "725-730-5718"
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "Cruickshank Mount 346",
                            FullName = "Louie O'Connell",
                            LoanId = 21,
                            Phone = "985-274-8215"
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "Raul Locks 1199",
                            FullName = "Juliana Romaguera",
                            LoanId = 19,
                            Phone = "630-228-9959"
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "Wolff Islands 144",
                            FullName = "Freddie Cummerata",
                            LoanId = 8,
                            Phone = "938-653-4282"
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "Kihn Lodge 431",
                            FullName = "Vernon Pouros",
                            LoanId = 16,
                            Phone = "986-428-7341"
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "Crona Inlet 134",
                            FullName = "Leopold Veum",
                            LoanId = 4,
                            Phone = "682-981-2508"
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "Thalia Orchard 859",
                            FullName = "Izaiah Crona",
                            LoanId = 22,
                            Phone = "912-571-0684"
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "Brenna Neck 1104",
                            FullName = "Sunny Mayer",
                            LoanId = 22,
                            Phone = "852-234-3478"
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "Wilford Light 1499",
                            FullName = "Graham Padberg",
                            LoanId = 14,
                            Phone = "914-755-2595"
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "Grady Fork 1049",
                            FullName = "Tianna Cassin",
                            LoanId = 6,
                            Phone = "357-988-1061"
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "Veum Mountain 1635",
                            FullName = "Jordon Terry",
                            LoanId = 7,
                            Phone = "922-259-8705"
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "Hugh Fall 278",
                            FullName = "Greyson Considine",
                            LoanId = 27,
                            Phone = "869-795-3808"
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "Bradtke Circle 383",
                            FullName = "Shanna Stracke",
                            LoanId = 16,
                            Phone = "741-291-0801"
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "Ebba Station 1353",
                            FullName = "Velda Schimmel",
                            LoanId = 6,
                            Phone = "654-470-2095"
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookLoanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BookReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysToLoan")
                        .HasColumnType("int");

                    b.Property<bool?>("ReturnedInTime")
                        .HasColumnType("bit");

                    b.HasKey("LoanId");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            BookId = 28,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5204),
                            CustomerId = 22,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 2,
                            BookId = 16,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5654),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 3,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5667),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 4,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5674),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 5,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5681),
                            CustomerId = 21,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 6,
                            BookId = 8,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5688),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 7,
                            BookId = 25,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5694),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 8,
                            BookId = 16,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5701),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 9,
                            BookId = 3,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5707),
                            CustomerId = 29,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 10,
                            BookId = 1,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5713),
                            CustomerId = 21,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 11,
                            BookId = 2,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5719),
                            CustomerId = 22,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 12,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5726),
                            CustomerId = 6,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 13,
                            BookId = 25,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5732),
                            CustomerId = 11,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 14,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5738),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 15,
                            BookId = 28,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5744),
                            CustomerId = 20,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 16,
                            BookId = 2,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5750),
                            CustomerId = 1,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 17,
                            BookId = 7,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5756),
                            CustomerId = 12,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 18,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5762),
                            CustomerId = 1,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 19,
                            BookId = 26,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5769),
                            CustomerId = 6,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 20,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5775),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 21,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5781),
                            CustomerId = 14,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 22,
                            BookId = 23,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5787),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 23,
                            BookId = 13,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5793),
                            CustomerId = 17,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 24,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5799),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 25,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5805),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 26,
                            BookId = 9,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5811),
                            CustomerId = 6,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 27,
                            BookId = 8,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5817),
                            CustomerId = 10,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 28,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5823),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 29,
                            BookId = 15,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5828),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 30,
                            BookId = 18,
                            BookLoanDate = new DateTime(2022, 9, 22, 9, 36, 29, 27, DateTimeKind.Local).AddTicks(5834),
                            CustomerId = 22,
                            DaysToLoan = 30
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.HasOne("Labb1MVC_Simon.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1MVC_Simon.Models.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
