// <auto-generated />
using System;
using Labb1MVC_Simon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1MVC_Simon.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Amount = 1,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 2,
                            Amount = 2,
                            LoanId = 10
                        },
                        new
                        {
                            BookId = 3,
                            Amount = 1,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 4,
                            Amount = 4,
                            LoanId = 14
                        },
                        new
                        {
                            BookId = 5,
                            Amount = 4,
                            LoanId = 10
                        },
                        new
                        {
                            BookId = 6,
                            Amount = 3,
                            LoanId = 36
                        },
                        new
                        {
                            BookId = 7,
                            Amount = 5,
                            LoanId = 13
                        },
                        new
                        {
                            BookId = 8,
                            Amount = 4,
                            LoanId = 31
                        },
                        new
                        {
                            BookId = 9,
                            Amount = 1,
                            LoanId = 1
                        },
                        new
                        {
                            BookId = 10,
                            Amount = 5,
                            LoanId = 4
                        },
                        new
                        {
                            BookId = 11,
                            Amount = 3,
                            LoanId = 23
                        },
                        new
                        {
                            BookId = 12,
                            Amount = 5,
                            LoanId = 39
                        },
                        new
                        {
                            BookId = 13,
                            Amount = 4,
                            LoanId = 32
                        },
                        new
                        {
                            BookId = 14,
                            Amount = 5,
                            LoanId = 38
                        },
                        new
                        {
                            BookId = 15,
                            Amount = 2,
                            LoanId = 4
                        },
                        new
                        {
                            BookId = 16,
                            Amount = 2,
                            LoanId = 18
                        },
                        new
                        {
                            BookId = 17,
                            Amount = 2,
                            LoanId = 37
                        },
                        new
                        {
                            BookId = 18,
                            Amount = 4,
                            LoanId = 12
                        },
                        new
                        {
                            BookId = 19,
                            Amount = 4,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 20,
                            Amount = 4,
                            LoanId = 30
                        },
                        new
                        {
                            BookId = 21,
                            Amount = 1,
                            LoanId = 8
                        },
                        new
                        {
                            BookId = 22,
                            Amount = 5,
                            LoanId = 28
                        },
                        new
                        {
                            BookId = 23,
                            Amount = 3,
                            LoanId = 9
                        },
                        new
                        {
                            BookId = 24,
                            Amount = 1,
                            LoanId = 33
                        },
                        new
                        {
                            BookId = 25,
                            Amount = 5,
                            LoanId = 38
                        },
                        new
                        {
                            BookId = 26,
                            Amount = 2,
                            LoanId = 32
                        },
                        new
                        {
                            BookId = 27,
                            Amount = 1,
                            LoanId = 27
                        },
                        new
                        {
                            BookId = 28,
                            Amount = 5,
                            LoanId = 6
                        },
                        new
                        {
                            BookId = 29,
                            Amount = 2,
                            LoanId = 38
                        },
                        new
                        {
                            BookId = 30,
                            Amount = 5,
                            LoanId = 21
                        },
                        new
                        {
                            BookId = 31,
                            Amount = 1,
                            LoanId = 31
                        },
                        new
                        {
                            BookId = 32,
                            Amount = 2,
                            LoanId = 13
                        },
                        new
                        {
                            BookId = 33,
                            Amount = 1,
                            LoanId = 3
                        },
                        new
                        {
                            BookId = 34,
                            Amount = 2,
                            LoanId = 38
                        },
                        new
                        {
                            BookId = 35,
                            Amount = 3,
                            LoanId = 34
                        },
                        new
                        {
                            BookId = 36,
                            Amount = 1,
                            LoanId = 3
                        },
                        new
                        {
                            BookId = 37,
                            Amount = 5,
                            LoanId = 7
                        },
                        new
                        {
                            BookId = 38,
                            Amount = 5,
                            LoanId = 16
                        },
                        new
                        {
                            BookId = 39,
                            Amount = 5,
                            LoanId = 2
                        },
                        new
                        {
                            BookId = 40,
                            Amount = 5,
                            LoanId = 26
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Yost Locks 1089",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/657.jpg",
                            FullName = "Mckenzie Toy",
                            LoanId = 27,
                            Phone = "853-270-8073"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Meredith Parkways 449",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/112.jpg",
                            FullName = "Beryl Frami",
                            LoanId = 32,
                            Phone = "344-846-1905"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Shanel Mall 1254",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/30.jpg",
                            FullName = "Jevon Ullrich",
                            LoanId = 27,
                            Phone = "642-775-7564"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Summer Ridges 1676",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/651.jpg",
                            FullName = "Ole Hermann",
                            LoanId = 26,
                            Phone = "223-409-8423"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Schmitt Coves 1131",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/534.jpg",
                            FullName = "Hardy Luettgen",
                            LoanId = 20,
                            Phone = "299-528-8916"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Dicki Forge 1860",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/516.jpg",
                            FullName = "Augustus Gibson",
                            LoanId = 22,
                            Phone = "343-686-2888"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Hahn Isle 163",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/444.jpg",
                            FullName = "Juliana Lubowitz",
                            LoanId = 7,
                            Phone = "285-584-8306"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Haley Stravenue 722",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/565.jpg",
                            FullName = "Oran Rath",
                            LoanId = 8,
                            Phone = "573-499-7839"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Goyette Loaf 800",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/254.jpg",
                            FullName = "Kyle Turcotte",
                            LoanId = 26,
                            Phone = "915-630-9924"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Thompson Pike 1926",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/842.jpg",
                            FullName = "Sydni Doyle",
                            LoanId = 11,
                            Phone = "311-468-4651"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Koch Bypass 257",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/835.jpg",
                            FullName = "Darrel Schaden",
                            LoanId = 14,
                            Phone = "232-239-9872"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Marks Run 590",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/752.jpg",
                            FullName = "Jettie Gutmann",
                            LoanId = 27,
                            Phone = "597-585-8343"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "White Alley 190",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/178.jpg",
                            FullName = "Clement Zulauf",
                            LoanId = 34,
                            Phone = "964-397-6339"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Friesen Islands 2125",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/457.jpg",
                            FullName = "Vidal Roberts",
                            LoanId = 16,
                            Phone = "467-731-5913"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Hoeger Bypass 1743",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/433.jpg",
                            FullName = "Arnoldo Nicolas",
                            LoanId = 28,
                            Phone = "829-767-2849"
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "Miller Walk 112",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1027.jpg",
                            FullName = "Destinee Treutel",
                            LoanId = 38,
                            Phone = "778-288-1292"
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "Alex Knolls 160",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/615.jpg",
                            FullName = "Lucie Prohaska",
                            LoanId = 39,
                            Phone = "307-696-7438"
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "Pollich Creek 1808",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/273.jpg",
                            FullName = "Gabriel Simonis",
                            LoanId = 29,
                            Phone = "719-771-8436"
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "Claire Courts 2092",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1231.jpg",
                            FullName = "Berry Boehm",
                            LoanId = 3,
                            Phone = "653-906-2359"
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "Strosin Trace 2153",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/147.jpg",
                            FullName = "Tracey Sauer",
                            LoanId = 25,
                            Phone = "868-836-6265"
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "Garth Shoals 1211",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/277.jpg",
                            FullName = "Mafalda Nitzsche",
                            LoanId = 28,
                            Phone = "389-720-7389"
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "Lockman Rapid 2138",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/116.jpg",
                            FullName = "Catherine Abshire",
                            LoanId = 11,
                            Phone = "799-628-5226"
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "Rodriguez Port 1128",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/118.jpg",
                            FullName = "Aracely Kilback",
                            LoanId = 30,
                            Phone = "622-759-7430"
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "Retta Village 797",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/752.jpg",
                            FullName = "Blanca Zemlak",
                            LoanId = 23,
                            Phone = "761-803-6368"
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "Isobel Greens 661",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1095.jpg",
                            FullName = "Mazie Pfeffer",
                            LoanId = 37,
                            Phone = "937-362-8755"
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "Hassan Plains 629",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/561.jpg",
                            FullName = "Jerrod Prosacco",
                            LoanId = 40,
                            Phone = "221-837-2880"
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "Zula Dam 376",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/703.jpg",
                            FullName = "Garrick Lubowitz",
                            LoanId = 25,
                            Phone = "470-716-1595"
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "Evert Falls 2392",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/692.jpg",
                            FullName = "Audreanne Goyette",
                            LoanId = 39,
                            Phone = "345-359-6296"
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "Bartoletti Branch 1547",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1016.jpg",
                            FullName = "Darrel Emmerich",
                            LoanId = 39,
                            Phone = "529-754-5163"
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "Rutherford Motorway 485",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/746.jpg",
                            FullName = "Ruby Waters",
                            LoanId = 34,
                            Phone = "440-943-2153"
                        },
                        new
                        {
                            CustomerId = 31,
                            Address = "Murazik Highway 778",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/324.jpg",
                            FullName = "Columbus Bahringer",
                            LoanId = 30,
                            Phone = "784-944-1875"
                        },
                        new
                        {
                            CustomerId = 32,
                            Address = "Spencer Plaza 1633",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/589.jpg",
                            FullName = "Helena Ziemann",
                            LoanId = 15,
                            Phone = "471-388-2304"
                        },
                        new
                        {
                            CustomerId = 33,
                            Address = "Howe Courts 2285",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/732.jpg",
                            FullName = "Zaria McKenzie",
                            LoanId = 16,
                            Phone = "478-626-6850"
                        },
                        new
                        {
                            CustomerId = 34,
                            Address = "Casandra Ways 566",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1244.jpg",
                            FullName = "Dario Homenick",
                            LoanId = 5,
                            Phone = "685-295-6022"
                        },
                        new
                        {
                            CustomerId = 35,
                            Address = "Bode Field 1976",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/219.jpg",
                            FullName = "Edwina Miller",
                            LoanId = 14,
                            Phone = "682-896-2536"
                        },
                        new
                        {
                            CustomerId = 36,
                            Address = "Carleton Island 397",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/548.jpg",
                            FullName = "Khalid Howe",
                            LoanId = 23,
                            Phone = "392-911-7201"
                        },
                        new
                        {
                            CustomerId = 37,
                            Address = "Carmen Parkways 654",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/164.jpg",
                            FullName = "Bernie Pfannerstill",
                            LoanId = 8,
                            Phone = "455-825-9950"
                        },
                        new
                        {
                            CustomerId = 38,
                            Address = "Gusikowski Spur 1540",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/695.jpg",
                            FullName = "Judson Kshlerin",
                            LoanId = 7,
                            Phone = "760-579-1788"
                        },
                        new
                        {
                            CustomerId = 39,
                            Address = "Heathcote Lights 1521",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/140.jpg",
                            FullName = "Mollie Schinner",
                            LoanId = 31,
                            Phone = "523-801-6676"
                        },
                        new
                        {
                            CustomerId = 40,
                            Address = "Crooks Spur 2231",
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/133.jpg",
                            FullName = "Cesar Kulas",
                            LoanId = 29,
                            Phone = "433-430-6844"
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookLoanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BookReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysToLoan")
                        .HasColumnType("int");

                    b.Property<bool?>("ReturnedInTime")
                        .HasColumnType("bit");

                    b.HasKey("LoanId");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            BookId = 12,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(5758),
                            CustomerId = 1,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 2,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6070),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 3,
                            BookId = 15,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6083),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 4,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6090),
                            CustomerId = 11,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 5,
                            BookId = 10,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6097),
                            CustomerId = 6,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 6,
                            BookId = 11,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6104),
                            CustomerId = 38,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 7,
                            BookId = 9,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6110),
                            CustomerId = 38,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 8,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6117),
                            CustomerId = 31,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 9,
                            BookId = 32,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6123),
                            CustomerId = 36,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 10,
                            BookId = 4,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6130),
                            CustomerId = 28,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 11,
                            BookId = 1,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6136),
                            CustomerId = 10,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 12,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6143),
                            CustomerId = 4,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 13,
                            BookId = 34,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6149),
                            CustomerId = 19,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 14,
                            BookId = 34,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6156),
                            CustomerId = 12,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 15,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6162),
                            CustomerId = 21,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 16,
                            BookId = 39,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6168),
                            CustomerId = 34,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 17,
                            BookId = 30,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6174),
                            CustomerId = 10,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 18,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6181),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 19,
                            BookId = 24,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6186),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 20,
                            BookId = 27,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6197),
                            CustomerId = 12,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 21,
                            BookId = 22,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6204),
                            CustomerId = 11,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 22,
                            BookId = 6,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6211),
                            CustomerId = 36,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 23,
                            BookId = 4,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6217),
                            CustomerId = 31,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 24,
                            BookId = 36,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6223),
                            CustomerId = 14,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 25,
                            BookId = 35,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6229),
                            CustomerId = 32,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 26,
                            BookId = 29,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6235),
                            CustomerId = 34,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 27,
                            BookId = 17,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6241),
                            CustomerId = 25,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 28,
                            BookId = 29,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6247),
                            CustomerId = 16,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 29,
                            BookId = 30,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6253),
                            CustomerId = 7,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 30,
                            BookId = 19,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6259),
                            CustomerId = 18,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 31,
                            BookId = 38,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6266),
                            CustomerId = 3,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 32,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6272),
                            CustomerId = 25,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 33,
                            BookId = 29,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6278),
                            CustomerId = 27,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 34,
                            BookId = 1,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6285),
                            CustomerId = 40,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 35,
                            BookId = 20,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6291),
                            CustomerId = 38,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 36,
                            BookId = 25,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6297),
                            CustomerId = 27,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 37,
                            BookId = 31,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6303),
                            CustomerId = 30,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 38,
                            BookId = 21,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6309),
                            CustomerId = 13,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 39,
                            BookId = 2,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6315),
                            CustomerId = 9,
                            DaysToLoan = 30
                        },
                        new
                        {
                            LoanId = 40,
                            BookId = 38,
                            BookLoanDate = new DateTime(2022, 9, 22, 14, 46, 30, 320, DateTimeKind.Local).AddTicks(6320),
                            CustomerId = 37,
                            DaysToLoan = 30
                        });
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Loan", b =>
                {
                    b.HasOne("Labb1MVC_Simon.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1MVC_Simon.Models.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Labb1MVC_Simon.Models.Customer", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
